"""Generate the live Supabase SQL (btc15 v2) from fitted model coefficients.

Usage: python3 gen_sql.py model.json > sql/btc15_v2.sql
model.json = {"deploy_logit_small": {...}, "deploy_inwindow": {...}} as printed by research2.py
"""
import json, sys

m = json.load(open(sys.argv[1]))
L = m['deploy_logit_small']
feat_expr = {
    'z_15': 'f.z_15', 'z_60': 'f.z_60', 'z_240': 'f.z_240', 'rsi_14': 'f.rsi_14',
    'rangepos_60': 'f.rangepos_60', 'gap_15': 'f.gap_15', 'prev_move_z': 'f.prev_move_z',
    'rv_ratio': 'f.rv_ratio', 'ret_1': 'f.ret_1', 'rangepos_240': 'f.rangepos_240',
}
terms = ' + '.join(
    f"({c!r}::float8 * ((coalesce({feat_expr[n]}, {mu!r}) - {mu!r}) / {sd!r}))"
    for n, mu, sd, c in zip(L['features'], L['mean'], L['scale'], L['coef']))
logit = f"{L['intercept']!r} + {terms}"

print(f"""-- generated by research/gen_sql.py -- do not edit by hand
-- 10-feature logistic model, walk-forward tested on 1-minute Coinbase+Bitstamp data

alter table public.btc15_signals
  add column if not exists p_up float8,
  add column if not exists rv60 float8,
  add column if not exists model text not null default 'fade1h';

-- scorecard now tracks the new model only
create or replace view public.btc15_scorecard as
  select strength,
    count(*) filter (where correct is not null) as resolved,
    round(100.0 * avg(correct::int), 1) as hit_rate_pct,
    count(contract_price) as priced_trades,
    round(sum(pnl_per_contract), 2) as paper_pnl_per_1_contract,
    round(avg(contract_price), 3) as avg_entry
  from public.btc15_signals where model = 'logit10'
  group by strength;

-- refresh candles on every fetch so a minute read too early gets corrected
create or replace function research.ingest() returns int
language plpgsql security definer set search_path = research, public as $$
declare j record; n int := 0; js jsonb;
begin
  for j in select f.*, r.status_code, r.content
           from fetch_jobs f join net._http_response r on r.id = f.req_id
           where not f.done loop
    if j.status_code = 200 then
      js := j.content::jsonb;
      if j.src = 'cb' then
        insert into btc_1m(src, ts, o, h, l, c, v)
        select 'cb', to_timestamp((e->>0)::bigint), (e->>3)::float8, (e->>2)::float8, (e->>1)::float8, (e->>4)::float8, (e->>5)::float8
        from jsonb_array_elements(js) e
        where to_timestamp((e->>0)::bigint) between j.start_ts and j.end_ts
        on conflict (src, ts) do update set o = excluded.o, h = excluded.h, l = excluded.l, c = excluded.c, v = excluded.v;
      else
        insert into btc_1m(src, ts, o, h, l, c, v)
        select 'bs', to_timestamp((e->>'timestamp')::bigint), (e->>'open')::float8, (e->>'high')::float8, (e->>'low')::float8, (e->>'close')::float8, (e->>'volume')::float8
        from jsonb_array_elements(js->'data'->'ohlc') e
        where to_timestamp((e->>'timestamp')::bigint) between j.start_ts and j.end_ts
        on conflict (src, ts) do update set o = excluded.o, h = excluded.h, l = excluded.l, c = excluded.c, v = excluded.v;
      end if;
      update fetch_jobs set done = true, last_status = 200 where id = j.id;
    else
      update fetch_jobs set req_id = null, last_status = coalesce(j.status_code, -1) where id = j.id;
    end if;
    n := n + 1;
  end loop;
  return n;
end $$;

-- per-minute index proxy (average of Coinbase and Bitstamp), gap-filled
create or replace function research.px_series(t0 timestamptz, t1 timestamptz)
returns table(ts timestamptz, p float8, typ float8, gap float8)
language sql stable security definer set search_path = research as $$
  with g as (select gs as ts from generate_series(t0, t1, interval '1 minute') gs),
  x as (
    select b.ts, avg(b.o) p, avg((b.o+b.h+b.l+b.c)/4) typ,
           coalesce(max(b.c) filter (where b.src='cb') - max(b.c) filter (where b.src='bs'), 0) gap
    from btc_1m b where b.ts between t0 and t1 group by b.ts),
  j as (select g.ts, x.p, x.typ, x.gap, count(x.p) over (order by g.ts) grp from g left join x using (ts))
  select ts, first_value(p) over (partition by grp order by ts),
         coalesce(typ, first_value(p) over (partition by grp order by ts)), coalesce(gap, 0)
  from j;
$$;

-- model features at window start ws (uses prices up to and including the open of minute ws)
create or replace function research.btc15_features(ws timestamptz)
returns table(k float8, z_15 float8, z_60 float8, z_240 float8, rsi_14 float8, rangepos_60 float8,
              gap_15 float8, prev_move_z float8, rv_ratio float8, ret_1 float8, rangepos_240 float8, rv_60 float8,
              move_15 float8, move_60 float8, have_now boolean)
language sql stable security definer set search_path = research as $$
  with s as (select * from px_series(ws - interval '600 minutes', ws)),
  a as (
    select ts, p, typ, gap, ln(p) lp, ln(p) - lag(ln(p)) over w r1,
           row_number() over (order by ts desc) - 1 back
    from s window w as (order by ts)),
  b as (
    select *,
      stddev_samp(r1) over (order by ts rows 14 preceding) rv15,
      stddev_samp(r1) over (order by ts rows 59 preceding) rv60,
      stddev_samp(r1) over (order by ts rows 239 preceding) rv240,
      min(p) over (order by ts rows 59 preceding) lo60, max(p) over (order by ts rows 59 preceding) hi60,
      min(p) over (order by ts rows 239 preceding) lo240, max(p) over (order by ts rows 239 preceding) hi240,
      avg(gap) over (order by ts rows between 15 preceding and 1 preceding) gap15,
      lag(lp, 1) over (order by ts) lp1, lag(lp, 15) over (order by ts) lp15,
      lag(lp, 60) over (order by ts) lp60, lag(lp, 240) over (order by ts) lp240,
      lag(p, 15) over (order by ts) p15, lag(p, 60) over (order by ts) p60,
      lag(typ, 1) over (order by ts) typ1
    from a),
  rsi as (
    select 100 - 100 / (1 + nullif(sum(power(13/14.0, back) * greatest(r, 0)), 0)
                          / nullif(sum(power(13/14.0, back) * greatest(-r, 0)), 0)) v
    from (select back, p - lag(p) over (order by ts) r from a) q where r is not null),
  now_ as (select * from b where back = 0)
  select n.p,
    (n.lp - n.lp15) / (n.rv240 * sqrt(15)), (n.lp - n.lp60) / (n.rv240 * sqrt(60)), (n.lp - n.lp240) / (n.rv240 * sqrt(240)),
    (select v from rsi),
    (n.p - n.lo60) / nullif(n.hi60 - n.lo60, 0),
    n.gap15 / n.p * 1e4,
    ((n.typ1 - n.p15) / n.p) / (n.rv240 * sqrt(15)),
    n.rv15 / nullif(n.rv240, 0),
    n.lp - n.lp1, (n.p - n.lo240) / nullif(n.hi240 - n.lo240, 0), n.rv60, n.p - n.p15, n.p - n.p60,
    exists (select 1 from btc_1m where btc_1m.ts = ws)
  from now_ n;
$$;

create or replace function public.btc15_run()
returns void language plpgsql security definer set search_path = public, research as $$
declare
  ws timestamptz := date_trunc('hour', now()) + floor(extract(minute from now()) / 15) * interval '15 minutes';
  f record; pu float8; side_p float8;
begin
  -- 1) settle finished windows on the 60-second average proxy (typical price of the final minute)
  update btc15_signals s set
    end_price = x.typ,
    outcome = case when x.typ >= s.start_price then 'up' else 'down' end,
    correct = (case when x.typ >= s.start_price then 'up' else 'down' end) = s.call
  from (
    select s2.id, avg((b.o+b.h+b.l+b.c)/4) typ
    from btc15_signals s2 join research.btc_1m b on b.ts = s2.window_end - interval '1 minute'
    where s2.end_price is null and s2.window_end <= now() - interval '2 minutes'
    group by s2.id) x
  where x.id = s.id;

  -- fallback for old-model rows or missing minute data: use the 5-minute price checks after 10 min
  update btc15_signals s set
    end_price = e.ep,
    outcome = case when e.ep >= s.start_price then 'up' else 'down' end,
    correct = (case when e.ep >= s.start_price then 'up' else 'down' end) = s.call
  from (select s3.id, (select pc.price from price_checks pc
                       where pc.asset_id = 'b9efe938-65b8-4c9c-8b3c-9047236d4c2a'
                         and pc.checked_at >= s3.window_end and pc.checked_at < s3.window_end + interval '5 min'
                       order by pc.checked_at limit 1) ep
        from btc15_signals s3 where s3.end_price is null and s3.window_end <= now() - interval '10 minutes') e
  where e.id = s.id and e.ep is not null;

  update btc15_signals set pnl_per_contract = case when correct then 1 - contract_price else -contract_price end
  where correct is not null and contract_price is not null and pnl_per_contract is null;

  -- 2) post the call for the current window once its first minute is in (skip if more than 5 min late)
  if exists (select 1 from btc15_signals where window_start = ws) then return; end if;
  if now() > ws + interval '5 minutes' then return; end if;
  select * into f from research.btc15_features(ws);
  if f.k is null or not f.have_now or f.rv_60 is null or f.z_240 is null then return; end if;

  pu := 1 / (1 + exp(-({logit})));
  side_p := greatest(pu, 1 - pu);

  insert into btc15_signals(window_start, window_end, start_price, move_15m, move_60m, strength, call, p_up, rv60, model)
  values (ws, ws + interval '15 minutes', round(f.k::numeric, 2), round(f.move_15::numeric, 2), round(f.move_60::numeric, 2),
          case when side_p >= 0.55 then 'strong' else 'weak' end,
          case when pu >= 0.5 then 'up' else 'down' end, pu, f.rv_60, 'logit10');
end $$;
""")
